spring:
  datasource:
    url: 'jdbc:h2:file:C:\Users\lnadrowski\repository\microservices\todo-app\todo-db'
    username: sa
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /todo